import TablaDiario from "./TablaDiario";

const ListaLibroDiario = () => {
const datosEjemplo = [
  {
    numero: 1,
    fecha: "27/08/2024",
    operacion: "Banco nación",
    debe: 3750,
    haber: 0,
    tipo: "Permutativa",
  },
  {
    numero: 1,
    fecha: "27/08/2024",
    operacion: "Valores a depositar",
    debe: 0,
    haber: 3750,
    tipo: "Permutativa",
  },
  {
    numero: 2,
    fecha: "27/08/2024",
    operacion: "Obligaciones a pagar",
    debe: 1200,
    haber: 0,
    tipo: "Permutativa",
  },
  {
    numero: 2,
    fecha: "27/08/2024",
    operacion: "Banco nación",
    debe: 0,
    haber: 1200,
    tipo: "Permutativa",
  },
  {
    numero: 3,
    fecha: "27/08/2024",
    operacion: "Caja",
    debe: 2150,
    haber: 0,
    tipo: "Modificatva",
  },
  {
    numero: 3,
    fecha: "27/08/2024",
    operacion: "Valores a depositar",
    debe: 2150,
    haber: 0,
    tipo: "Modificatva",
  },
  {
    numero: 3,
    fecha: "27/08/2024",
    operacion: "Ventas",
    debe: 0,
    haber: 4300,
    tipo: "Modificatva",
  },
  {
    numero: 3,
    fecha: "27/08/2024",
    operacion: "CMV",
    debe: 2900,
    haber: 0,
    tipo: "Modificatva",
  },
  {
    numero: 3,
    fecha: "27/08/2024",
    operacion: "Mercadería",
    debe: 0,
    haber: 2900,
    tipo: "Modificatva",
  },
  {
    numero: 4,
    fecha: "03/09/2024",
    operacion: "Muebles y útiles",
    debe: 850,
    haber: 0,
    tipo: "Permutativa",
  },
  {
    numero: 4,
    fecha: "03/09/2024",
    operacion: "Obligaciones a pagar",
    debe: 0,
    haber: 850,
    tipo: "Permutativa",
  },
  {
    numero: 5,
    fecha: "04/09/2024",
    operacion: "Banco nación",
    debe: 2150,
    haber: 0,
    tipo: "Permutativa",
  },
  {
    numero: 5,
    fecha: "04/09/2024",
    operacion: "Valores a depositar",
    debe: 0,
    haber: 2150,
    tipo: "Permutativa",
  },
  {
    numero: 6,
    fecha: "05/09/2024",
    operacion: "Gastos por publicidad",
    debe: 300,
    haber: 0,
    tipo: "Modificativa",
  },
  {
    numero: 6,
    fecha: "05/09/2024",
    operacion: "Caja",
    debe: 0,
    haber: 300,
    tipo: "Modificativa",
  },
  {
    numero: 7,
    fecha: "06/09/2024",
    operacion: "Intereses por mora",
    debe: 250,
    haber: 0,
    tipo: "Modificativa",
  },
  {
    numero: 7,
    fecha: "06/09/2024",
    operacion: "Proveedores",
    debe: 0,
    haber: 250,
    tipo: "Modificativa",
  },
  {
    numero: 8,
    fecha: "07/09/2024",
    operacion: "Caja",
    debe: 2000,
    haber: 0,
    tipo: "Permutativa",
  },
  {
    numero: 8,
    fecha: "07/09/2024",
    operacion: "Adelanto de clientes",
    debe: 0,
    haber: 2000,
    tipo: "Permutativa",
  },
  {
    numero: 9,
    fecha: "08/09/2024",
    operacion: "Mercaderías",
    debe: 3500,
    haber: 0,
    tipo: "Modificativa",
  },
  {
    numero: 9,
    fecha: "08/09/2024",
    operacion: "Banco nación",
    debe: 0,
    haber: 3150,
    tipo: "Modificativa",
  },
  {
    numero: 9,
    fecha: "08/09/2024",
    operacion: "Descuento obtenido",
    debe: 0,
    haber: 350,
    tipo: "Modificativa",
  },
];


  return (
    <div>
      <TablaDiario datosLibro={datosEjemplo} />
    </div>
  );
};

export default ListaLibroDiario;
